### ISSUE TITLE
Stuck at microk8s enable kubeflow -  Try `microk8s enable kubeflow` instead 

### ISSUE THREAD

**Issue by AdeloreSimiloluwa** [juju-solutions/bundle-kubeflow#300] opened 2021-01-21 15:06 UTC
Tried setting kebflow up in ubuntu with Microk8s
I followed the following steps
  ```
1) sudo snap install microk8s --classic --channel=latest/edge
  2) sudo microk8s status --wait-ready
  3) sudo usermod -a -G microk8s $USER
  4) sudo chown -f -R $USER ~/.kube
  5) microk8s.enable dns dashboard storage
  6) microk8s.enable kubeflow --bundle=lite
  7) choose a password
  8) microk8s.kubectl get all --all-namespaces
  9) http://10.64.140.43.xip.io
```
Here is the problem, It just stops working at `microk8s.enable kubeflow --bundle=lite`. This is the error I got
![image (7)](https://user-images.githubusercontent.com/62348760/105368992-1646dc80-5bd0-11eb-92cb-b018b1af7132.png)

I tried again with `microk8s enable kubeflow` but I got the same error

**Comment by knkski** [comment] 2021-01-22 04:50
@AdeloreSimiloluwa: You should run this command as a non-root user (try `whoami` or `id` to double-check your current user). Closing this issue as I believe the non-root check is working as intended, feel free to reopen if you encounter this error as a non-root user.

**Closed by knkski** 2021-01-22 04:50 UTC
