### ISSUE TITLE
Notebook servers renders a blank page

### ISSUE THREAD

**Issue by VariableDeclared** [juju-solutions/bundle-kubeflow#297] opened 2021-01-19 08:20 UTC
Hi,

When deploying Kubeflow on Charmed Kubernetes the notebooks servers page renders a blank page, it appears that jupyter is missing some configuration around the gateways allowing access to the page. More info in the linked comment.

[Workaround]

The patch applied in https://github.com/kubeflow/kubeflow/issues/5480#issuecomment-754439487

Cheers
Peter

**Comment by knkski** [comment] 2021-01-20 17:52
This should now work with the master branch of this repo. Closing since we now have functional UI tests to catch regressions like this so it should definitely be fixed, but feel free to reopen if redeploying with master (or latest stable bundle) doesn't fix it for you

**Closed by knkski** 2021-01-20 17:52 UTC
